<header>
       <img src="./IMG/logo.png" alt="logo"/>
       <div>
            <div id="search-bar">
                <input type="text" placeholder="Search" />
            </div>
            <form action="FrontController" method="POST">
                     <button type="submit" name="accion" value="carrito"><img src="./IMG/carrito.png" alt="carrito"/></button>
                     <button type="submit" name="accion" value="login">Login</button>
                     <button type="submit" name="accion" value="registro">Registro</button> 
            </form>
       </div>
</header>